version: "3"
services:
  postgres:
    image: postgres:14-alpine
    hostname: postgres
    container_name: psql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gofermart
      POSTGRES_USER: userm
      POSTGRES_PASSWORD: 12345678
#    volumes:
#      - ./data:/var/lib/postgresql/data

  api:
    container_name: gofermart
    build: ./
    volumes:
      - .:/app
    command: |
      sh -c "/wait
      migrate -path ./schema -database 'postgres://userm:12345678@postgres:5432/gofermart?sslmode=disable' up
      ./cmd/accrual/accrual_linux_amd64"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432